# Generated by Django 3.2.6 on 2021-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djancommerce', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prod_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
