# Generated by Django 3.2.6 on 2021-08-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djancommerce', '0007_cartitem_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self', 'self'), ('alibaba delivery', 'alibaba delivery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'paypal'), ('click', 'click'), ('payme', 'payme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('On the way', 'On the way'), ('delivered', 'delivered')], default='To be confirmed', max_length=50),
        ),
    ]
